package com.like.common.sample.objectbox;

import io.objectbox.annotation.Entity;
import io.objectbox.annotation.Generated;
import io.objectbox.annotation.Id;
import io.objectbox.annotation.apihint.Internal;

@Entity
public class ObjectBoxInfo {
    @Id
    private long id;
    private String name;
    @Generated(1745258133)
    @Internal
    /** This constructor was generated by ObjectBox and may change any time. */
    public ObjectBoxInfo(long id, String name) {
        this.id = id;
        this.name = name;
    }
    @Generated(1066432907)
    public ObjectBoxInfo() {
    }
    public long getId() {
        return id;
    }
    public void setId(long id) {
        this.id = id;
    }
    public String getName() {
        return name;
    }
    public void setName(String name) {
        this.name = name;
    }

}
